### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by MichaelSchoolConnect** [FirebaseExtended/codelab-contentrecommendation-android#2]
Hi, can anyone help me with this?
![Screenshot_2021-01-18 BigQuery – content-recommendat… – Google Cloud Platform](https://user-images.githubusercontent.com/20036643/104922841-e74c2300-59a3-11eb-8b44-976592cc5270.png)

**Comment by MichaelSchoolConnect** [comment]
Oh, this was due to my billing account.

TODO: Enable your billing account

**Comment by anujraghuvanshi** [comment]
I have all things working fine, Yet I am getting the error while using this sample dataset.
Any possible issue ?
