### ISSUE TITLE
/usr/bin/python3: Error while finding module specification for 'model.recommendation_model_launcher_keras' (ModuleNotFoundError: No module named 'model')

### ISSUE THREAD

**Issue by SanushRadalage** [FirebaseExtended/codelab-contentrecommendation-android#4]
This issue appears when I run 

`!python -m model.recommendation_model_launcher_keras \
  --run_mode "train_and_eval" \
  --encoder_type "bow" \
  --training_data_filepattern "/tmp/recommendation/examples/train_movielens_1m.tfrecord" \
  --testing_data_filepattern "/tmp/recommendation/examples/test_movielens_1m.tfrecord" \
  --model_dir "/tmp/recommendation/reco_model" \
  --params_path "model/sample_config.json" \
  --batch_size 32 \
  --learning_rate 0.01 \
  --steps_per_epoch 1000 \
  --num_epochs 1000 \
  --num_eval_steps 1000 \
  --gradient_clip_norm 1.0 \
  --max_history_length 10`  this code.

**Comment by SanushRadalage** [comment]
When running this code, you must get all of the files in _examples\lite\examples\recommendation\ml\model_ directory into _/content/model_ directory

**Comment by SanushRadalage** [comment]
When running this code, you must get all of the files in _examples\lite\examples\recommendation\ml\model_ directory into _/content/model_ directory

**Comment by anujraghuvanshi** [comment]
@SanushRadalage - I am getting the same issue, while I am running my code on google colab
Any idea on how I can fix there and get it working?

**Comment by SanushRadalage** [comment]
@anujraghuvanshi Hey when running this code, you must get all of the files in examples\lite\examples\recommendation\ml\model directory into /content/model directory
